const obj= {
    "ref": "refs/heads/test-2",
    "before": "0000000000000000000000000000000000000000",
    "after": "24ba301c6b2262e3f24913f629e2d9b04b39f2ec",
    "repository": {
        "id": 665794601,
        "node_id": "R_kgDOJ684KQ",
        "name": "testGitHooks",
        "full_name": "KiRiLLPers/testGitHooks",
        "private": false,
            "email": "89154832+KiRiLLPers@users.noreply.github.com",
            "id": 89154832,
            "avatar_url": "https://avatars.githubusercontent.com/u/89154832?v=4",
            "url": "https://api.github.com/users/KiRiLLPers",
            "html_url": "https://github.com/KiRiLLPers",
            "followers_url": "https://api.github.com/users/KiRiLLPers/followers",
            "following_url": "https://api.github.com/users/KiRiLLPers/following{/other_user}",
            "gists_url": "https://api.github.com/users/KiRiLLPers/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/KiRiLLPers/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/KiRiLLPers/subscriptions",
            "organizations_url": "https://api.github.com/users/KiRiLLPers/orgs",
            "repos_url": "https://api.github.com/users/KiRiLLPers/repos",
            "events_url": "https://api.github.com/users/KiRiLLPers/events{/privacy}",
            "received_events_url": "https://api.github.com/users/KiRiLLPers/received_events",
            "type": "User",
            "site_admin": false
        },
        "html_url": "https://github.com/KiRiLLPers/testGitHooks",
        "description": null,
        "fork": false,
        "url": "https://github.com/KiRiLLPers/testGitHooks",
        "forks_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/forks",
        "keys_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/teams",
        "hooks_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/hooks",
        "issue_events_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/issues/events{/number}",
        "events_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/events",
        "assignees_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/assignees{/user}",
        "branches_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/branches{/branch}",
        "tags_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/tags",
        "blobs_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/languages",
        "stargazers_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/stargazers",
        "contributors_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/contributors",
        "subscribers_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/subscribers",
        "subscription_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/subscription",
        "commits_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/contents/{+path}",
        "compare_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/merges",
        "archive_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/downloads",
        "issues_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/issues{/number}",
        "pulls_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/labels{/name}",
        "releases_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/releases{/id}",
        "deployments_url": "https://api.github.com/repos/KiRiLLPers/testGitHooks/deployments",
        "created_at": 1689216863,
        "updated_at": "2023-07-13T03:05:57Z",
        "pushed_at": 1689238056,
        "git_url": "git://github.com/KiRiLLPers/testGitHooks.git",
        "ssh_url": "git@github.com:KiRiLLPers/testGitHooks.git",
        "clone_url": "https://github.com/KiRiLLPers/testGitHooks.git",
        "svn_url": "https://github.com/KiRiLLPers/testGitHooks",
        "homepage": null,
        "size": 3,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "HTML",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master",
        "stargazers": 0,
        "master_branch": "master"
    },
    "pusher": {
        "name": "KiRiLLPers",
        "email": "89154832+KiRiLLPers@users.noreply.github.com"
    },
    "sender": {
        "login": "KiRiLLPers",
        "id": 89154832,
        "node_id": "MDQ6VXNlcjg5MTU0ODMy",
        "avatar_url": "https://avatars.githubusercontent.com/u/89154832?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/KiRiLLPers",
        "html_url": "https://github.com/KiRiLLPers",
        "followers_url": "https://api.github.com/users/KiRiLLPers/followers",
        "following_url": "https://api.github.com/users/KiRiLLPers/following{/other_user}",
        "gists_url": "https://api.github.com/users/KiRiLLPers/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/KiRiLLPers/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/KiRiLLPers/subscriptions",
        "organizations_url": "https://api.github.com/users/KiRiLLPers/orgs",
        "repos_url": "https://api.github.com/users/KiRiLLPers/repos",
        "events_url": "https://api.github.com/users/KiRiLLPers/events{/privacy}",
        "received_events_url": "https://api.github.com/users/KiRiLLPers/received_events",
        "type": "User",
        "site_admin": false
    },
    "created": true,
    "deleted": false,
    "forced": false,
    "base_ref": null,
    "compare": "https://github.com/KiRiLLPers/testGitHooks/commit/24ba301c6b22",
    "commits": [
        {
            "id": "24ba301c6b2262e3f24913f629e2d9b04b39f2ec",
            "tree_id": "b169a7f74d93e42c1465bd170c34a97359b0d0aa",
            "distinct": true,
            "message": "where branch name test2",
            "timestamp": "2023-07-13T15:47:30+07:00",
            "url": "https://github.com/KiRiLLPers/testGitHooks/commit/24ba301c6b2262e3f24913f629e2d9b04b39f2ec",
            "author": {
                "name": "Кирилл",
                "email": "kirill.pershin@itwis.org"
            },
            "committer": {
                "name": "Кирилл",
                "email": "kirill.pershin@itwis.org"
            },
            "added": [],
            "removed": [],
            "modified": [
                "index.js"
            ]
        }
    ],
    "head_commit": {
        "id": "24ba301c6b2262e3f24913f629e2d9b04b39f2ec",
        "tree_id": "b169a7f74d93e42c1465bd170c34a97359b0d0aa",
        "distinct": true,
        "message": "where branch name test2",
        "timestamp": "2023-07-13T15:47:30+07:00",
        "url": "https://github.com/KiRiLLPers/testGitHooks/commit/24ba301c6b2262e3f24913f629e2d9b04b39f2ec",
        "author": {
            "name": "Кирилл",
            "email": "kirill.pershin@itwis.org"
        },
        "committer": {
            "name": "Кирилл",
            "email": "kirill.pershin@itwis.org"
        },
        "added": [],
        "removed": [],
        "modified": [
            "index.js"
        ]
    }
}

// console.log(obj.ref.split("/").slice(-1).join(""))
console.log(obj)
